### ISSUE TITLE
Enable Link-Time Optimization (LTO)

### ISSUE THREAD

**Issue by zamazan4ik** [mr-adult/JFC#2]
Hi!

I noticed that in the `Cargo.toml` file Link-Time Optimization (LTO) for the project is not enabled. I suggest switching it on since it will reduce the binary size (always a good thing to have) and will likely improve the application's performance a bit (since this is a parsin tool, PGO also could help here but I guess it's a bit overhead for the tool).

I suggest enabling LTO only for the Release builds so as not to sacrifice the developers' experience while working on the project since LTO consumes an additional amount of time to finish the compilation routine. If you think that a regular Release build should not be affected by such a change as well, then I suggest adding an additional `dist` or `release-lto` profile where additionally to regular `release` optimizations LTO will also be added. Such a change simplifies life for maintainers and others interested in the project persons who want to build the most performant version of the application. Using ThinLTO should also help to reduce the build-time overhead with LTO. If we enable it on the Cargo profile level, users, who install the application with `cargo install`, will get the LTO-optimized version "automatically". E.g., check `cargo-outdated` Release [profile](https://github.com/kbknapp/cargo-outdated/blob/master/Cargo.toml#L48).

Basically, it can be enabled with the following lines:

```
[profile.release]
lto = true
```

I have made quick tests (Fedora 40) by adding `lto = true` to the Release profile. The results are the following:
* Release: 1.2 Mib
* Release + `lto = true`: 992 Kib
* Release + `lto = true` + `strip = true`: 864 Kib

Thank you.

P.S. In the README file, there is a veeeeeery small type "doc.rust-land.org" instead of "doc.rust-lang.org". The link is fine but the text has a typo. I didn't want to create a separate issue for that. You want to enable LTO for the project, this typo can be fixed in that PR too.

**Comment by mr-adult** [comment]
Thank you for the suggestion! LTO is new to me so I'll do some reading about it, but based on your synopsis it seems like a clear positive change. I'll try to get that merged in the next couple days.
